### ISSUE TITLE
Update link to angular2-swing

### ISSUE THREAD

**Issue by mashhoodr** [gajus/swing#105]
Hello @gajus,

I was wondering if it is possible to update the link of the angular2-swing repo, since the owner of the current base repo has become unresponsive (https://github.com/ksachdeva/angular2-swing/issues/23). I am willing to take on the issues and missing features in my fork 
(fork: https://github.com/recurship/angular2-swing) (discussion: https://github.com/ksachdeva/angular2-swing/pull/19) if the link gets updated, publish a new npm package linked to this new fork. 

Thanks.

**Comment by gajus** [comment]
Have you asked @ksachdeva if he can add you as a contributor instead?

**Comment by mashhoodr** [comment]
@gajus we asked him for an update a month ago, but he didnt reply. I can try asking him that as well.

**Comment by gajus** [comment]
Usually authors simply get too busy to make the changes because they are no longer using the package themselves. In this case, finding a contributor is preferred. Probably the case here too.

**Comment by mashhoodr** [comment]
@gajus sure stuff, I have asked the author to add me as a contributor - if there is no reply I will ping here again. Thanks!

**Comment by tobiasmuecksch** [comment]
For the record:
https://github.com/ksachdeva/angular2-swing/issues/23#issuecomment-289391445
https://github.com/ksachdeva/angular2-swing/pull/19

**Comment by gajus** [comment]
Lets give it 24 hours.

If there is no response, I will add you two as contributors to https://github.com/gajus/angular-swing and you can release angular v2 upgrade (under a new major version). Does that sound like a good solution or do you prefer to create a new namespace for the project?

**Comment by mashhoodr** [comment]
@gajus that would be kinda ideal, however Im not sure how the support / documentation will work for Angular1 then. Do you know of any repo already doing this?

**Comment by gajus** [comment]
> @gajus that would be kinda ideal, however Im not sure how the support / documentation will work for Angular1 then. Do you know of any repo already doing this?

There is no active development for angular 1. It is enough to release the new version under a new major tag and reference angular 1 users to the last tag that supports v1.

**Comment by mashhoodr** [comment]
@gajus I have access to the other repository now, so I will continue to maintain that one.
