### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by Sparkomatic** [gajus/swing#106]
I get the impression there has been no responses to this repo recently. It's of great value to me because I use it through the angular2-swing wrapper. I have been waiting for the prepend functionality to be merged here: https://github.com/gajus/swing/pull/93 for a while.
If nobody is tending to this repo anymore, can someone else take it over (if Gajus is happy with this) along with  the relevant npm repository too.

**Comment by gajus** [comment]
> If nobody is tending to this repo anymore, can someone else take it over (if Gajus is happy with this) along with the relevant npm repository too.

@Sparkomatic The repo is not dead. I am not actively developing, though. If you raise a PR, I will review them.
