### ISSUE TITLE
How do I use this with normal Node JS?

### ISSUE THREAD

**Issue by wahlforss** [gajus/swing#108]
I have been trying to use Swing with Node JS, but with no luck. 
window.swing = require('swing'); 
is not working with normal Node JS, why is this? What is the window object?

I would prefer not to use Webpack.

Any help would be much appreciated, I'm a complete beginner with Node.

**Comment by gajus** [comment]
This library is designed to work with webpack.

**Comment by wahlforss** [comment]
Thank you, how do I change from webpack dev to normal webpack?
