### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by wahlforss** [gajus/swing#109]
Where do I find the config file for changing the distance a card needs to be dragged to be thrown?

**Comment by tenshis** [comment]
You need to create a config variable like this:

```
const config = {
        throwOutConfidence: (xOffset, yOffset, element) => {
                //decide if throw was successful
                const xConfidence = Math.min(Math.abs(xOffset) / element.offsetWidth, 1);
                const yConfidence = Math.min(Math.abs(yOffset) / element.offsetHeight, 1);
                return Math.max(xConfidence, yConfidence);
        }
};
```

And then initialize the stack using it as parameter

`stack = Swing.Stack(config);`

Then you can play with the confidence levels in throwOutConfidence to change the distance you want.

**Comment by PeterTheOne** [comment]
You can also just leave `throwOutConfidence` as is and set 
```
const throwOutThreshold = 0.33;
const config = {
	isThrowOut: function (xOffset, yOffset, element, throwOutConfidence) {
		return throwOutConfidence >= throwOutThreshold;
	},
};
```
The threshold is in relation to the card width or height, depending on which is larger, see `throwOutConfidence`.
