### ISSUE TITLE
Examples not running.  Getting error "Cannot read property 'Stack' of undefined"

### ISSUE THREAD

**Issue by PlanetPush** [gajus/swing#118]
When attempting to run any of the examples I get an error:
"Cannot read property 'Stack' of undefined"

This seems to be because window.swing is undefined.

Please can you advise?

Cheers

**Comment by gajus** [comment]
Have you followed the instructions https://github.com/gajus/swing/tree/master/examples ?

**Comment by PlanetPush** [comment]
I had not and I am a clown.
:-(
