### ISSUE TITLE
Minification problem

### ISSUE THREAD

**Issue by thomasmcevoy** [gajus/swing#137]
I keep getting the following error when bundling my project for production:

TypeError: "r is undefined"
    G Random.vue:1
    Le VueJS
    G Random.vue:1
    VueJS 7
    a es6.promise.js:75
    M es6.promise.js:92
    c _microtask.js:18
vue.runtime.esm.js:1888

I've traced it to swing.js and not the vue-swing wrapper. It works fine in my dev environment, I only get the error in production. Does anyone know what's going on here?

**Comment by gajus** [comment]
Too little information. Error seems to originate from Vue though.
