### ISSUE TITLE
Cannot convert a Symbol value to a number

### ISSUE THREAD

**Issue by powerbuoy** [gajus/swing#142]
When I try to programmatically throw out a card using `card.throwOut(Swing.Direction.LEFT, 0)` I get an error saying `Uncaught TypeError: Cannot convert a Symbol value to a number` on line 46 of Card.js: `var isHorizontal = Math.abs(fromX) > Math.abs(fromY);`.

**Comment by gajus** [comment]
Should be an easy fix.

**Comment by powerbuoy** [comment]
Awesome :) Is there a workaround in the meantime?

**Comment by gajus** [comment]
No, but you can contribute a fix.

**Comment by gajus** [comment]
Just in case, I don't have capacity to work on this.

**Comment by powerbuoy** [comment]
Oh OK, tbh I have no idea how to fix it?

**Comment by powerbuoy** [comment]
FWIW a workaround seems to be to simply pass in `-1` for left and `1` for right.
