### ISSUE TITLE
Swipe down doesn't trigger throwout

### ISSUE THREAD

**Issue by Almis90** [gajus/swing#143]
When I swipe the card down the event below doesn't trigger, it only trigger for left, right and up. When I swiped down the event that triggers is throwin. What I'm doing wrong?

````
    stack.on('throwout', (event) => {
      console.log(event.throwDirection);
    });

**Comment by gajus** [comment]
I am pretty sure that is not a feature.

https://github.com/gajus/swing/issues/55
