### ISSUE TITLE
Lodash bloats the bundle size up, but it not used in that much places

### ISSUE THREAD

**Issue by pal03377** [gajus/swing#144]
The dependency of this library on lodash.js bloats the bundle size up by at least 500kB for me. It seems lodash is only used in about 5 places in the code - and in all instances there is now a pretty well supported browser-native function that can replace it. Maybe we could save that 500kB?

**Comment by gajus** [comment]
See related issues.

https://github.com/gajus/swing/issues?q=+lodash

**Comment by pal03377** [comment]
Thanks for providing a link. May I ask why dropping lodash as a dependency completely is a thing you don't consider? Having less dependencies always seems to be a plus to me, and by dropping it, people wouldn't even have to do own additional configuration on their side for tree shaking.

I'm using rollup and as far as I see it does not seem to recognize the possible tree shake for this module by itself... but when using the version from the PR, my build instantly becomes > 500kB smaller.

I wouldn't normally suggest dropping a dependency and potentially having a bit more work without it. However, considering that my PR even _decreases_ the number of lines, I think this may be a useful option.
