### ISSUE TITLE
Make only the top card swipeable

### ISSUE THREAD

**Issue by MurWade** [gajus/swing#15]
Any idea how we can limit to one card being swipeable, the top card? I can think of a quick and dirty fix but i am sure there must be an easier way to do this and make only the card on top swipable. 

If any help, it would be much appreciated. I might actually just try to implement this my self and add a option to the stack config.  any help would be appreciated . Thank you

**Comment by gajus** [comment]
You can do that using CSS.

```css
:not(:first-child) {
    pointer-events: none;
}
```
