### ISSUE TITLE
config.throwOutConfidence does not seem to be working

### ISSUE THREAD

**Issue by joshuaforliberty** [gajus/swing#23]
```js
config = {
    throwOutConfidence: function (offset, element) {
        console.log('Check');
        return Math.min(Math.abs(offset/2) / element.offsetWidth, 1);
    }
};
```

Seems to have no effect on console or throw confidence.

**Comment by m52go** [comment]
I seem to be having the same issue.

**Comment by gajus** [comment]
Please setup an example using jsfiddle or jsbin.

**Comment by m52go** [comment]
As I was setting up the JS Bin, I realized I'm at fault.

1. I wasn't passing in the config variable: `stack = gajus.Swing.Stack(config);`

2. (somewhat related) once config variable is included, you can make threshold for swipes lower by making the top part of the ratio bigger (scaling it by a multiple > 1). Assuming your setup is similar to @gajus's examples.

That was my ultimate goal. Sorry @gajus for the trouble. Swing is incredible!
