### ISSUE TITLE
Debug output

### ISSUE THREAD

**Issue by tobiasmuecksch** [gajus/swing#26]
There is annoying debug output on line 3994 (in the distributed version) in version 1.1.3. As far as I can tell it already got fixed in the sources (by this commit https://github.com/gajus/swing/commit/ce8dc33549f1e04a3dc6d67a050a42d73d2c6f5c) but it is still unfixed in the release/swing.js file.

Could you please release a new version 1.1.4 which contains this fix?
Thanks in advance!

**Comment by gajus** [comment]
https://github.com/gajus/swing/pull/31
