### ISSUE TITLE
Reduce the distance before card is thrown

### ISSUE THREAD

**Issue by b3nhartl3y** [gajus/swing#27]
Hello all, 

Sorry for my naivety - I'm sure this is extremely simple but I can't seem to get it to function correctly. What do I need to put in the config to reduce the distance the user must move the card before it's considered thrown?

Kind regards,
Ben

**Comment by tobiasmuecksch** [comment]
I did it this way:

```
config = {
	throwOutConfidence: function (offset, element) {
		return Math.min(Math.abs(offset) / (element.offsetWidth / 2), 1); // Fix dropout distance by dividing by 2
	},

	maxRotation: 45
};
```

**Comment by b3nhartl3y** [comment]
Perfect thank you!
