### ISSUE TITLE
Event callback does not define event name

### ISSUE THREAD

**Issue by unbug** [gajus/swing#34]
Event has the type of current event name should be good.

**Comment by gajus** [comment]
Please rephrase the issue/question. It is incomprehensible at the moment.

**Comment by unbug** [comment]
such as:
```javascirpt
stack.on('throwoutend', function (e) {
        console.log(e.type);// throwoutend
      });
```

**Comment by gajus** [comment]
It [does not](https://github.com/gajus/swing#swing-events-event-object). What would be the purpose of defining the event name if you are the one who is setting up the listeners?

```js
stack.on('throwoutend', (e) => {
    console.log(e.type); // throwoutend

    // You already know that the event type is throwoutend.
});
```
