### ISSUE TITLE
Swing example with full list of dependencies. Development version

### ISSUE THREAD

**Issue by frankenstein-uk** [gajus/swing#37]
Hello,

I found this plugin very neat and smooth working.
Only issue is that I can't figure out how to setup development version, so I could do modifications.

It works fine if I include swing-master/dist/swing.min.js, which is production version.

But I want to use files from src folder. I tried to include them all and kept getting errors, such as "require not defined" etc.

Could someone create an example, which would have all dependencies loaded from CDN in right order?

Thank you

**Comment by unbug** [comment]
This project is base on browserify,if you want to include it yourself,you should `npm install` to install all the dependences and your project must be browserify,if you project is base on requireJS,you can check out [swing-amd](https://github.com/unbug/swing-amd).

**Comment by frankenstein-uk** [comment]
@unbug  Thank you for clarification. This wan't mention anywhere, and I was not familiar with Browserify. Now I managed to bundle working file

**Comment by unbug** [comment]
You should check out [swing-amd](https://github.com/unbug/swing-amd),its optimized for android.

**Comment by gajus** [comment]
Project can be built using [gulp](https://github.com/gajus/swing/blob/master/gulpfile.js).
