### ISSUE TITLE
Disable reordering of 'li' elements

### ISSUE THREAD

**Issue by ricokoiv** [gajus/swing#42]
How would it be possible to disable the reordering of 'li' elements when clicking on a card which is not on the top of the stack. As of right now, when I click on the second card 'ul' reorders itself and the second card comes on top.

**Comment by gajus** [comment]
What is the intent? The purpose of reordering the stack is to bring the card you are holding to the top of the stack.

**Comment by gajus** [comment]
No explanation for the intent.
