### ISSUE TITLE
If the draggable div isn't on the center, it's useless

### ISSUE THREAD

**Issue by yedort** [gajus/swing#44]
It's good when the draggable div is on the center, otherwise it's useless. How to make it work according as how close to the outside of the parent element the draggable div is?

**Comment by gajus** [comment]
Not constructive.

**Comment by gajus** [comment]
I have proposed a possible solution at https://github.com/gajus/swing/issues/7#issuecomment-126396940. PR is welcome.

**Comment by yedort** [comment]
Like I said, this way, it's useless.

**Comment by gajus** [comment]
The current implementation does not implement drop zones. The current implementation relies on `throwOutConfidence`. By default, card is considered out of the deck when its been dragged more than half of its width. However, you can [overwrite `throwOutConfidence` in configuration](https://github.com/gajus/swing#configuration) to relay on custom logic, e.g. how near the card is your card deck (zone designed for dropping the card).

**Comment by yedort** [comment]
I'm not very good at JS. So can you help me about it? Not when the element is dragged from original position with the half of its width, but when it's dragged to the outside the parent element with the half of its width.
