### ISSUE TITLE
How to get all thrown cards back?

### ISSUE THREAD

**Issue by yedort** [gajus/swing#47]
How to get all thrown cards back at once? What function to use?

**Comment by gajus** [comment]
You would need to write custom logic for that. This requirement is too specific to be part of the library itself.

**Comment by yedort** [comment]
Like, how can I get a thrown card back with or without animation, for example? If you show me a way, I can do it.

**Comment by gajus** [comment]
You need to create a new card matching properties of the original and add it to the stack.
