### ISSUE TITLE
package.json refers to nonexistent dist/index.js file

### ISSUE THREAD

**Issue by jmhnilbog** [gajus/swing#49]
It looks like v3.0.0 isn't set up correctly for nom distribution. The package.son file `main` entry is for a file that does not exist. Not sure what the correct entry point here would be.

**Comment by jmhnilbog** [comment]
It looks like performing a bit of a dance will allow this to work from node/browserify as expected.

```
require('swing/dist/swing.js');
var swing = gajus.Swing; // or global.gajus.Swing
```

**Comment by gajus** [comment]
I will look into this first thing tomorrow morning.

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/swing/tree/3.0.1
