### ISSUE TITLE
How to show example console log ?

### ISSUE THREAD

**Issue by daveeel** [gajus/swing#50]
Tried the official demo and downloaded the example and don't see any console logs. 

Is something changed or missed ?

**Comment by daveeel** [comment]
Tried old demo of version 1.1.4, it shows console log as documented
but that of 3.0.1 doesn't ...

**Comment by gajus** [comment]
This is a bug. It has been fixed in 3.0.2.

**Comment by Xwalk-Company** [comment]
Same issue in 3.0.2, in the example too.
