### ISSUE TITLE
Question: How to get Sister events in Meteor?

### ISSUE THREAD

**Issue by primeminister** [gajus/swing#51]
I am trying to get Swing into a meteor app, but meteor will not pickup the custom events triggered by Sister.

I also tried `stack.on('throwout', function (e) {` but that is not fired too.

**Comment by gajus** [comment]
Ignore Meteor.

https://github.com/gajus/swing/tree/master/examples/card-stack

Does this code example work to you?

**Comment by primeminister** [comment]
The cards work, can drag the cards out of the deck, so yes. All works except The stack.on console.log is not show in my console when I drag a card out of the deck.

**Comment by primeminister** [comment]
WAIT! It works! version 3.0.2 works and 3.0.1 did not! Thanks gajus!
