### ISSUE TITLE
Adding new LI element to the bottom of the stack

### ISSUE THREAD

**Issue by barocsi** [gajus/swing#62]
How can I dynamically add a new card to the bottom of the stack with UL/LI?

Currently when I try the following, it reorders the list and new cards appear on the top of the stack.
1. Adding LI element to the beginning of the UL
2. Creating new card from the LI
3. UL gets reordered, newly added LI element is being sent to the top of the stack

Thanks

**Comment by miczed** [comment]
Why don't you have a look at the posts here:
https://github.com/gajus/swing/issues/4

By default swing automatically adds new cards on top of the stack but if you modify the source code of the Card constructor, you can add cards at the bottom of the stack.

**Comment by gajus** [comment]
Thank you @miczed
