### ISSUE TITLE
Reset stack - how?

### ISSUE THREAD

**Issue by paulcanning** [gajus/swing#69]
Is there a method built in for reseting a stack of cards and having them thrown back into the pile?

If not, and I need to loop through each card and call card.throwIn(), how can I get the cards current X and Y, so they can animate from where they are currently on the page?

**Comment by gajus** [comment]
@paulcanning Have you figured it out at the end?

If yes, please document the solution and close the issue.

**Comment by paulcanning** [comment]
Sorry for the late reply. I find it amusing that the author doesn't know how to do this lol

I ended up doing

```
$.each(cards, function(a, b) {
                var x = Math.floor(Math.random() * 601) - 300;
                var y = Math.floor(Math.random() * 201) - 100;

                b.throwIn(x, y);
            });
```

**Comment by gajus** [comment]
Thank you.
