### ISSUE TITLE
Restrict Y axis placement?

### ISSUE THREAD

**Issue by paulcanning** [gajus/swing#70]
When I drag a card out of the pile, I can place it quite high above the pile, or quite below, on the Y axis.

Is there a way to limit the range on the Y axis so card appear more "in line" with the pile?

[Example](http://imgur.com/tZTtRlt) (see how far down I can place a card)

**Comment by jony89** [comment]
I think this will help you https://github.com/gajus/swing/issues/48

**Comment by gajus** [comment]
@paulcanning Have you figured it out at the end?

If yes, please document the solution and close the issue.

**Comment by gkTim** [comment]
To archive this you need to use the transform option in the config and transform the element manually: 

```
transform: (element, x, y, r) => {
     y = 0;
     element.style['transform'] = `translate3d(0, 0, 0) translate(${x}px, ${y}px) rotate(${r}deg)`;
},
```
