### ISSUE TITLE
Method for disabling swing/card

### ISSUE THREAD

**Issue by nadangergeo** [gajus/swing#71]
When the user clicks on a card, it zooms in to the card (with some css magic), showing more content, and is scrollable. The problem is that the user can't scroll because swing is still active on the card. Is there any easy way to disable swing with a method or "hack"?

I've tried listening to events and running `event.preventDefault()`, no luck.

**Comment by nadangergeo** [comment]
So... no I destroy and recreate a card to mimick the disable effect... but for some reason, scrolling using touchevents on the card won't work (regular scrolling still works, but scrolling on mobile doesn't). Could this hunk be responsible? https://github.com/gajus/swing/blob/master/src/card.js#L134-L137

**Comment by nadangergeo** [comment]
Yepp, e.preventDefault(); was the issue. But I'm guessing that it is essential. What should I do? A general disabled state would be preferred. I will see If I can implement that :)

**Comment by ihh** [comment]
I'm having a problem related to this: if the user clicks on a card below the current card (the edges of non-top cards are exposed by the neat nth-element rotation effect) then it comes to the top. I want to be able to disable cards temporarily, any hints?

**Comment by nadangergeo** [comment]
@ihh There's a PR by @mattblang that achieves this (#94).

@nielskrijger @mattblang 
Basically, as MC Hammer so elegantly put it, you can't touch this!
![Hammertime](http://media1.giphy.com/media/GPuVXyAmkMco0/giphy.gif)

There's one case which #94 doesn't solve (AFAIK), the case of actually being able to interact with the child elements when allowMoment is false.

My case:
The cards has react-swipeable-views with images as child (when in open-state). Using allowMovement works for disallowing the card from being draggable while in this state, but react-swipeable-views is not swipable. It works fine in desktop and when simulating mobile in chrome's dev tool, but not on a real phone (tested on iOS 9 safari).

Do we need to have method which toggles the touchmove-events in Swing? Or is exposing Hammer like @nielskrijger propsed the way to go?

My current workaround is destroying the card from the Swing stack and readding when the card is closed xD

**Comment by Stian-Scholtz** [comment]
My solution was to apply/bind the following css to the elements which should not be draggable/swingable:

pointer-events: none;

Hope this helps someone.
