### ISSUE TITLE
Changing card.throwOut speed

### ISSUE THREAD

**Issue by makenai** [gajus/swing#72]
Is it possible to change the speed of card.throwOut? For example, if I do a drag with my finger, the speed is natural. However, if I issue a card.throwOut(-1,0) or similar, the card flashes by so quick you almost don't notice.

**Comment by Leigende** [comment]
Same, I need it , swing is awesome !

**Comment by mattblang** [comment]
Yeah, this would be very nice to be able to customize. I am specifying a throwOut point off screen, and currently it is thrown out so fast I hardly notice it.

**Comment by numerized** [comment]
same here, played around with the lib, I couldn't find any ways

**Comment by josephraymond** [comment]
Has anyone come to a resolution with this?

**Comment by rajeevriitm** [comment]
I eventually did it using animation, with translate and rotate.once animation is done, just pop the card.

**Comment by gajus** [comment]
> I eventually did it using animation, with translate and rotate.once animation is done, just pop the card.

@rajeevriitm  Do you have a demo to share with others?

**Comment by rajeevriitm** [comment]
I have worked on Angular 2 . You can follow the same idea. Initially I have defined the animations. 

 ```
 animations: [
  trigger("throw",[
    transition("* => accepted",[
      animate('400ms ease-in',style({transform: ' translate(800px,-400px) rotate(-90deg)'}))
      ]),
    transition("* => rejected",[
      animate('400ms ease-in',style({transform: ' translate(-800px,-400px) rotate(90deg)'}))
      ])
    ])
  ]
```
Here `accept` and `reject` translate it to right and left with rotation just like throwing. 

Then to trigger the animation

```
    this.anim[0]= status; //trigger the correct animation for throwing, either right or left.
    setTimeout( () => { // waits for throwing animation to finish.
      this.anim[0]= undefined  ; // to stop animation.
      let hunt = this.hunts.shift(); // to remove the card
    })
```

This can be achieved with regular css. Hope it helps.

**Comment by gajus** [comment]
Thank you.

**Comment by majaray** [comment]
> I have worked on Angular 2 . You can follow the same idea. Initially I have defined the animations.
> 
> ```
> animations: [
>  trigger("throw",[
>    transition("* => accepted",[
>      animate('400ms ease-in',style({transform: ' translate(800px,-400px) rotate(-90deg)'}))
>      ]),
>    transition("* => rejected",[
>      animate('400ms ease-in',style({transform: ' translate(-800px,-400px) rotate(90deg)'}))
>      ])
>    ])
>  ]
> ```
> Here `accept` and `reject` translate it to right and left with rotation just like throwing.
> 
> Then to trigger the animation
> 
> ```
>     this.anim[0]= status; //trigger the correct animation for throwing, either right or left.
>     setTimeout( () => { // waits for throwing animation to finish.
>       this.anim[0]= undefined  ; // to stop animation.
>       let hunt = this.hunts.shift(); // to remove the card
>     })
> ```
> This can be achieved with regular css. Hope it helps.

Do you have the solution with using pure css?
I have no idea how does the Angular animation works.

**Comment by Miserlou** [comment]
A simple fix is to lower the velocity value on this line: https://github.com/gajus/swing/blob/master/src/Card.js#L345
