### ISSUE TITLE
Using Swing with React.

### ISSUE THREAD

**Issue by cameronolivier** [gajus/swing#73]
I'm implementing Swing with React - is there a wrapper for this (I've looked but can't find anything) - otherwise any way I can use it directly? 

Thanks.

**Comment by jperl** [comment]
Hi I just found this https://github.com/ssanjun/react-swing

**Comment by cameronolivier** [comment]
Awesome! Thank you @jperl - looks like just what I needed 👍

**Comment by reidblomquist** [comment]
@cameronolivier Not a huge fan of that react-swing as it needs lazy loading to work right. I'd honestly say you might be better off using swing directly. Direct JS implementations vary widely based on your setup (isomorphic or non, etc) - but imports loader should be a good place to look if you have a more basic non isomorphic setup. Did you end up using react-swing?
