### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by sarceda** [gajus/swing#74]
I can swipe cards on examples, but I don't get any message on the console.log.

**Comment by Xwalk-Company** [comment]
Same issue in 3.0.2, in the example too.

**Comment by Xwalk-Company** [comment]
I found the error only appears only for those who recovers the file "swing.js". At line 169, the createCard function, just replace "name" with "eventName"
`	    stack.createCard = function (element) {
	        var card = undefined,
	            events = undefined;
	
	        card = (0, _card2['default'])(stack, element);
	
	        events = ['throwout', 'throwoutend', 'throwoutleft', 'throwoutright', 'throwin', 'throwinend', 'dragstart', 'dragmove', 'dragend'];
	
	        // Proxy Card events to the Stack.
	        events.forEach(function (eventName) {
	            card.on(eventName, function (data) {
	                eventEmitter.trigger(eventName, data);
	            });
	        });
	
	        index.push({
	            element: element,
	            card: card
	        });
	
	        return card;
	    };`

**Comment by gajus** [comment]
This shouldn't be an issue in recent releases.
