### ISSUE TITLE
dragstart doesn't have a corresponding dragend on simple click 

### ISSUE THREAD

**Issue by Forkest** [gajus/swing#89]
This is really a big problem: I'm trying to add a class that indicates that the element is being dragged, and I cannot remove the class reliably, so it messes up everything.

To reproduce, just click a card without moving the mouse pointer (or moving it a pixel or two).

**Comment by Forkest** [comment]
You should not mix Hammer and own events for dragging. Either use Hammer's panstart, panmove, and panend, or handle mousedown/touchstart, mousemove/touchmove, mouseup/touchend all manually. In the code now it is the first method that is used for dragmove and dragend, but the second one for dragstart.

**Comment by Forkest** [comment]
I've left current events as is, with the custom early dragstart and late Hammer's panend, fixing only the issue of events inconsistency by triggering dragend on mouseup/touchend when dragstart has been already sent and panstart has not been yet received.

**Comment by jony89** [comment]
+1 for this. @gajus could u merge it ? i'm having this issue as well.

btw @gajus i would be happy to help maintain this library since i see you are not so active here.

**Comment by gajus** [comment]
@jony89 I have reached out to @Forkest asking to rebase the PR.

https://github.com/gajus/swing/pull/90#issuecomment-275654774
