### ISSUE TITLE
npm ist outdated

### ISSUE THREAD

**Issue by mys3lf** [gajus/swing#96]
Your package on npm is really old. You should update it.

**Comment by ihh** [comment]
If I might try to rephrase this a little more graciously: first of all, thanks for making this package. It does seem like there are a lot of people interested in using it. I do appreciate how maintaining a successful package can start to seem like a burden. I for one would love to take advantage of recent developments. I'm sure there are many like me who would benefit from an updated node package and/or some more detailed build instructions. Thanks again.

**Comment by mys3lf** [comment]
I don't want to impolite and I think @ihh is right, i should be a little more thankful and express myself a little more nicely. Maybe its because i'm german and we are direct without any detours. Of course i'm thankful for your time and work.

**Comment by gajus** [comment]
I believe this has been addressed. The NPM package contains the latest version.

https://github.com/gajus/swing/tree/v4.2.0
