### ISSUE TITLE
How to create a min version of this package

### ISSUE THREAD

**Issue by premtemp1** [gajus/swing#98]
Hello,
  I am using an an old version of this package (1.1.4) and it had a swing.min,js file.. However, this file is missing in the new bower package

Can you tell me how to create this package ?.. Is there a reason why the .min is not included

**Comment by yojona** [comment]
https://github.com/yojona/swingy

**Comment by gajus** [comment]
> Can you tell me how to create this package ?.. Is there a reason why the .min is not included

The package is designed to be consumed by module bundlers such as webpack or Browserify. You can build a min bundle with either of those programs.
